// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {compare} from '../models';

export function ApplyLinesLeftToRight(arg1:string,arg2:number,arg3:number):Promise<compare.FileComparisonResult>;

export function ApplyLinesRightToLeft(arg1:string,arg2:number,arg3:number):Promise<compare.FileComparisonResult>;

export function ChooseDirectory():Promise<string>;

export function ChooseFile():Promise<string>;

export function CloseFileComparison(arg1:string):Promise<void>;

export function CloseFolderComparison(arg1:string):Promise<void>;

export function CopyFileLeftToRight(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function CopyFileRightToLeft(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DiscardFileChanges(arg1:string):Promise<compare.FileComparisonResult>;

export function HomeDirectory():Promise<string>;

export function ListDirectory(arg1:string):Promise<compare.DirectoryListing>;

export function OpenFileComparison(arg1:string,arg2:string,arg3:string):Promise<compare.FileComparisonResult>;

export function OpenFolderComparison(arg1:string,arg2:string,arg3:string):Promise<compare.FolderComparisonResult>;

export function PreviewFile(arg1:string):Promise<compare.FilePreview>;

export function RefreshFileComparison(arg1:string):Promise<compare.FileComparisonResult>;

export function RefreshFolderComparison(arg1:string,arg2:string,arg3:string):Promise<compare.FolderComparisonResult>;

export function RevealPath(arg1:string):Promise<void>;

export function SaveFileComparison(arg1:string,arg2:string):Promise<compare.FileComparisonResult>;
