// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyLinesLeftToRight(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyLinesLeftToRight'](arg1, arg2, arg3);
}

export function ApplyLinesRightToLeft(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyLinesRightToLeft'](arg1, arg2, arg3);
}

export function ChooseDirectory() {
  return window['go']['main']['App']['ChooseDirectory']();
}

export function ChooseFile() {
  return window['go']['main']['App']['ChooseFile']();
}

export function CloseFileComparison(arg1) {
  return window['go']['main']['App']['CloseFileComparison'](arg1);
}

export function CloseFolderComparison(arg1) {
  return window['go']['main']['App']['CloseFolderComparison'](arg1);
}

export function CopyFileLeftToRight(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopyFileLeftToRight'](arg1, arg2, arg3);
}

export function CopyFileRightToLeft(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopyFileRightToLeft'](arg1, arg2, arg3);
}

export function DiscardFileChanges(arg1) {
  return window['go']['main']['App']['DiscardFileChanges'](arg1);
}

export function HomeDirectory() {
  return window['go']['main']['App']['HomeDirectory']();
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function OpenFileComparison(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenFileComparison'](arg1, arg2, arg3);
}

export function OpenFolderComparison(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenFolderComparison'](arg1, arg2, arg3);
}

export function PreviewFile(arg1) {
  return window['go']['main']['App']['PreviewFile'](arg1);
}

export function RefreshFileComparison(arg1) {
  return window['go']['main']['App']['RefreshFileComparison'](arg1);
}

export function RefreshFolderComparison(arg1, arg2, arg3) {
  return window['go']['main']['App']['RefreshFolderComparison'](arg1, arg2, arg3);
}

export function RevealPath(arg1) {
  return window['go']['main']['App']['RevealPath'](arg1);
}

export function SaveFileComparison(arg1, arg2) {
  return window['go']['main']['App']['SaveFileComparison'](arg1, arg2);
}
